### ISSUE TITLE
3.1.0版本不能依赖，版本号一提升就报错。

### ISSUE THREAD

**Issue by pengjunhong** [zhiqiang-series/smart-show#44]
![1615618026(1)](https://user-images.githubusercontent.com/18617995/111022031-27aba880-840b-11eb-949b-7f41f2e683e6.jpg)

**Comment by zhiqiang-series** [comment]
你好，问题已解决，请使用最新版本3.1.2。

**Comment by zhiqiang-series** [comment]
你好，问题已解决，请使用最新版本3.1.3。

**Comment by zhiqiang-series** [comment]
你好，问题已解决，请使用最新版本3.1.3。
