### ISSUE TITLE
库自带的Dialog大小怎么调整呢？

### ISSUE THREAD

**Issue by panyy** [zhiqiang-series/smart-show#47]

**Comment by zhiqiang-series** [comment]
继承，重新provideDialogWidth方法。https://github.com/zhiqiang-series/smart-show/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89-Dialog-%E5%AE%BD%E5%BA%A6
高度暂时没有相关api。不过这个模块很快进行大的重构。

**Comment by panyy** [comment]
好的
